 1.Write a python code to create a array in different ways

In [1]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50,60,70,80])
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [3]:
type(arr)

numpy.ndarray

In [4]:
# for tup
tup = (11,12,13,14,15,16,17,18)
arr1 = np.array(tup)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18])

In [6]:
# for list
list1 = [11,21,31,41,51,61,71,81]
arr3 = np.array(list1)
arr3

array([11, 21, 31, 41, 51, 61, 71, 81])

2.Array Creation:

a. Create a 1D Numpy array containing the first 12 positive integers as arr1.

b. Create a 1D Numpy array1 with 20 elements containing integers between 0 and 12 using linspace.

In [7]:
# a
arry = np.arange(1,13)
arry

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
# b
arry1 = np.linspace(1,30,15)
arry1

array([ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429,
       11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714,
       21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ])

3. Find all atrributes of array1 and array2.

In [10]:
array1 = np.arange(1,13)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
array2 = np.linspace(1,30,15)
array2

array([ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429,
       11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714,
       21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ])

In [12]:
# Attributes of array1
array1.dtype      #the datatype of values in the array

dtype('int32')

In [13]:
array1.ndim           #the dimension of the array1

1

In [14]:
array1.size           #number of elements in the array 

12

In [15]:
array1.nbytes          #the space occupied by all the elements

48

In [16]:
array1.itemsize          #the space occupied by the single element.

4

In [17]:
# Attributes of array2
array2.dtype

dtype('float64')

In [18]:
array2.ndim

1

In [19]:
array2.size

15

In [20]:
array2.nbytes

120

In [21]:
array2.itemsize

8

4.Apply measure and describe the data to above arrays usind Numpy.

In [22]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Measure of central tendency for array1

In [23]:
array1.mean()

6.5

In [24]:
np.median(array1)

6.5

# Measure of spread of array1

In [26]:
# range
range1 = np.max(array1)-np.min(array1)
range1

11

In [27]:
# std
np.std(array1)

3.452052529534663

In [28]:
# varince
np.var(array1)

11.916666666666666

###  IQR of array1

In [29]:
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [32]:
q3 = np.percentile(array1,75)
q3

9.25

In [33]:
q1 = np.percentile(array1,25)
q1

3.75

In [34]:
IQR = q3-q1
IQR

5.5

# find outlier

In [35]:
lower_limit = q1-(1.5*IQR)
lower_limit

-4.5

In [36]:
upper_limit = q3+(1.5*IQR)
upper_limit

17.5

In [37]:
array1>upper_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [38]:
array1<lower_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

# Measure of central tendency for array1

In [40]:
array2

array([ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429,
       11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714,
       21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ])

In [41]:
np.mean(array2)

15.5

In [42]:
np.median(array2)

15.500000000000002

# Measure of spread

In [44]:
range2  =np.max(array2)-np.min(array2)
range2

29.0

In [45]:
np.var(array2)

80.09523809523812

In [46]:
np.std(array2)

8.949594297801331

# IQR

In [47]:
q3 = np.percentile(array2,75)
q3

22.75

In [48]:
q1 = np.percentile(array2,25)
q1

8.25

In [49]:
IQR = q3-q1
IQR

14.5

# find outlier of array2

In [50]:
array2

array([ 1.        ,  3.07142857,  5.14285714,  7.21428571,  9.28571429,
       11.35714286, 13.42857143, 15.5       , 17.57142857, 19.64285714,
       21.71428571, 23.78571429, 25.85714286, 27.92857143, 30.        ])

In [51]:
lower_limit = q1-(1.5*IQR)
lower_limit

-13.5

In [52]:
upper_limit = q3+(1.5*IQR)
upper_limit

44.5

In [53]:
array2>upper_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [54]:
array2<lower_limit

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])